import { Montserrat } from "next/font/google";
import "./globals.css"; // Import your global CSS
import "../components/fontawesome"; // Adjust the path to your fontawesome.js file

// Correct font weight values (no `100 900`, use individual weights)
const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Specify valid weights
  subsets: ["latin"], // Ensure Latin subset is loaded
  variable: "--font-montserrat", // Variable name for Montserrat
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
